import 'comic.dart';

final List<Comic> comics = [
  Comic(
    title: 'Spider-Man: Blue',
    author: 'Jeph Loeb',
    price: 14.99 * 70, 
    imageUrl: 'https://i.pinimg.com/736x/1d/a4/3d/1da43d8742b591be0dd6557410e701b7.jpg',
    category: 'Spider-Man',
    description: 'Это трогательная история о Питере Паркере и Гвен Стейси.',
    quantity: 5,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Spider-Man: Kraven\'s Last Hunt',
    author: 'J.M. DeMatteis',
    price: 17.99 * 70, 
    imageUrl: 'https://cdn1.ozone.ru/s3/multimedia-1-d/6933150625.jpg',
    category: 'Spider-Man',
    description: 'Последняя охота Кравена на Человека-паука.',
    quantity: 3,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Batman: Year One',
    author: 'Frank Miller',
    price: 19.99 * 70, 
    imageUrl: 'https://s3.amazonaws.com/www.covernk.com/Covers/L/B/Batman+Year+One/batmanyearonetradepaperback1.jpg',
    category: 'Batman',
    description: 'Происхождение Бэтмена.',
    quantity: 7,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Batman: The Long Halloween',
    author: 'Jeph Loeb',
    price: 22.99 * 70, 
    imageUrl: 'https://static.tvtropes.org/pmwiki/pub/images/batman_long_halloween_cover.jpg',
    category: 'Batman',
    description: 'Годовая тайна для Бэтмена.',
    quantity: 4,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Teenage Mutant Ninja Turtles: City at War',
    author: 'Kevin Eastman',
    price: 15.99 * 70, 
    imageUrl: 'https://vignette.wikia.nocookie.net/tmnt/images/b/b0/Idw91.jpg/revision/latest?cb=20190214074102',
    category: 'Ninja Turtles',
    description: 'Черепашки сталкиваются с городской войной.',
    quantity: 6,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Teenage Mutant Ninja Turtles: The Last Ronin',
    author: 'Kevin Eastman',
    price: 24.99 * 70, 
    imageUrl: 'https://i.dailymail.co.uk/1s/2024/04/11/21/83526179-13298943-image-a-142_1712867277901.jpg',
    category: 'Ninja Turtles',
    description: 'Последний выживший Черепашка ищет мести.',
    quantity: 2,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'X-Men: Days of Future Past',
    author: 'Chris Claremont',
    price: 18.99 * 70, 
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/5/5b/True_Believers_X-Men_-_Pyro_Vol_1_1.jpg/revision/latest?cb=20191004182739',
    category: 'X-Men',
    description: 'Путешествие во времени, чтобы изменить будущее мутантов.',
    quantity: 4,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'X-Men: The Dark Phoenix Saga',
    author: 'Chris Claremont',
    price: 21.99 * 70, 
    imageUrl: 'https://cdn.marvel.com/u/prod/marvel/i/mg/9/20/58b5d00e39b3c/clean.jpg',
    category: 'X-Men',
    description: 'История о разрушительной силе Темной Феникс.',
    quantity: 3,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Avengers: Infinity War',
    author: 'Jonathan Hickman',
    price: 23.99 * 70, 
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/0/05/Infinity_War_Vol_1_2.jpg/revision/latest/scale-to-width-down/650?cb=20190417003856',
    category: 'Avengers',
    description: 'Битва за судьбу вселенной против Таноса.',
    quantity: 5,
    isFavorite: false,
    isInCart: false,
  ),
  Comic(
    title: 'Avengers: Endgame',
    author: 'Jason Aaron',
    price: 25.99 * 70, 
    imageUrl: 'https://i.pinimg.com/736x/7c/f5/55/7cf55562edf630e4cf5d734ab34da648.jpg',
    category: 'Avengers',
    description: 'Финальная битва за восстановление вселенной.',
    quantity: 6,
    isFavorite: false,
    isInCart: false,
  ),
];